language: go
go:
- 1.11
env:
  global:
    secure: EI1uZ9aRkZCAft/nMn9lJiEX+UQ4DiN7UdH+Ot94Ad5PQSbqy/P9rl8oStFub/EU+W/R+LpTpn3x7wIRu78v0ITzhsbmhRY2JRa3G10GMykOL6U6kBb23uIJepfbYypKNnjoraZ/su7VPbBaUkecDBkexO9p14yENvIl2gy3BUXeJRgdALiRn+C5CC0PKsiX437WHlYCk3rSZdSe0EUtyqoNqoFslU4lHnDBO4WWgqe3wEcksruFk6dDDKZB3SvezJzCfpif344J46qXlM5pKwx0ytjCEV0pzL85i6XlmXIL/STUWnwUjMjid/RZfXndb9QnL90lgS1eALzMM4VH7wnbhtWcNNrFWv/rTbFvSxvIkBrAv1YU562w8ESGS+q/a+PyWUb1zVx9tLjf/U3qjfDx7p8tlcSE8AHw8HN4P4dqZLNC+47rGBzJZpYd+MIYy8mMo+s9GDWaypKAqLLtwuWL8KGm6HGyVn3yW+mEugpISl8/BFhqHl5z6B87yM3nq1k9d70DD12JLtt6s5Niu7h0PbPlrV9DqNPSvMI8C+kfYrBelLbrdJrvu6ImprB8Sb/q+AKRIrqBZF3KKIi/5zmRo++f0j8vMEv1qAIM5hMcZUlbmzSzgCw5e7FbiH7Wy4GerGlamTvwRkVMEVlM1wtM9R9ER5lYm6ZylwQoCZM=
before_install:
- go get github.com/mattn/goveralls
install:
- env GO111MODULE=on go mod download
script:
- env GO111MODULE=on go install
- env GO111MODULE=on go test ./... -coverprofile=cover.out
- goveralls -coverprofile=cover.out
before_deploy:
- go get github.com/mitchellh/gox
- env GO111MODULE=on gox
deploy:
  provider: releases
  api_key:
    secure: UPPT/X4VE4rjTljg8ur3bnPCckfJvqoSL9wD2pp+Kwwz4cA8vNVyDMkfPJqJSBT929zRZStRI76y2Dqv7HnKb8Hj4IjMjMKCS/4z1wcLPnK9RRHDScvgBo8dsK5fiQacy+krKCijbyhOIny7m8vLok3/XTdLGfDEfUehzQKhJUv0XVFTdYyIYkVaHIxeErg8KqRNuVTCNcBhD4OobrtI7DFXVc4wE45qBEqV57qKuMMK5jSZ+vYJSVa/K4xcBWeSG2uOdqlhqFSzFt8qXm9V1ayCH2Cbmi182kf47r3ErgJpl4DpbhPpO42Cu6Jg6FvArRfpTVtyNfFbT2vKMBkS66RSfQvDjcXYiiMcd990AX5sOGN/LbwJjZrrlLxZfT3SaMwWKOdWBwk9+yOAZ2aElUaC8TW+XiYDc6qf2aNgVsxmbcU1cnY13MLeYMvLIj4EMFH99YiYv5wld9mmEePy5Tkg0fLIH0i//ihDY0dXZxC1fuJyw0+6gmbKAeUqJQSNwQthUg40Sp1yIElzSHbvsP3wmakke32+i7uq8kODRKIHGBzqZU7+koA9G/tpr3qoPxl9mnMnriVl8pHga3xF8TVcXw0JxmcwY1Gd+g77QxX3HJVcuVZhHx4g9q5AQr5+fVgcOwjdAnePEYPQ2KRnijCa8vuw0cBPMppZ2o1wsSM=
  skip_cleanup: true
  file:
  - postmanerator_darwin_386
  - postmanerator_darwin_amd64
  - postmanerator_freebsd_386
  - postmanerator_freebsd_amd64
  - postmanerator_freebsd_arm
  - postmanerator_linux_386
  - postmanerator_linux_amd64
  - postmanerator_linux_arm
  - postmanerator_netbsd_386
  - postmanerator_netbsd_amd64
  - postmanerator_netbsd_arm
  - postmanerator_openbsd_386
  - postmanerator_openbsd_amd64
  - postmanerator_windows_386.exe
  - postmanerator_windows_amd64.exe
  on:
    repo: sufry/postmanerator
    tags: true
